import React from "react";
import Head from "next/head";
import Layout from "../widget/Layout";
import { Hero, Category, Product, Card } from "../components";
export default function Home() {
  return (
    <>
      <Head>
        <title>E-Commerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Hero />
        <Category />
        <Product>
          <Card />
          <Card />
          <Card />
          <Card />
          <Card />
          <Card />
          <Card />
        </Product>
      </Layout>
    </>
  );
}
